# Site settings
title: Ahar's Blog
email: abdullah[at]ahar.sa
description: "a small dev blog"
baseurl: ""
url: "http://ahar411.github.io/"
username: "ahar411" 



# Build settings
markdown: kramdown
permalink: pretty


gems:
    - jekyll-sitemap
